# Generated by Django 4.0.4 on 2022-04-18 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('contact_mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('marketing_choice', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subscription', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=50, null=True)),
                ('subscription_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redirects',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('url_from', models.CharField(max_length=512)),
                ('url_to', models.CharField(max_length=512)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_redirects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
