# Generated by Django 4.0.4 on 2022-04-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirects',
            name='http_https',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=5),
            preserve_default=False,
        ),
    ]
