# Generated by Django 4.0.4 on 2022-04-18 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redirects_http_https'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirects',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
