# Generated by Django 4.2.1 on 2023-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_redirects_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirects',
            name='le_body',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='redirects',
            name='le_cert',
            field=models.FileField(max_length=512, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='redirects',
            name='le_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
